FIREBASE_CREDENTIALS = '''{
  "type": "service_account",
  "project_id": "leiloesdevproject",
  "private_key_id": "xxxxxxxxxxxxxxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEv...",
  "client_email": "firebase-adminsdk-xxxxx@leiloesdevproject.iam.gserviceaccount.com",
  "client_id": "1234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/..."
}'''

FIREBASE_DATABASE_URL = "https://leiloesdevproject-default-rtdb.firebaseio.com/"

[theme]
base="dark"